version: "3.1"

services:
  apache:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 127.0.0.1:8081:80
    volumes:
      - ./src:/var/www/html/

  mysql:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 127.0.0.1:3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    volumes:
      - ./mysql-data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 127.0.0.1:8082:80
    environment:
      - PMA_ARBITRARY=1